version: '3'
services:
  user:
    build:
      context: ./
      dockerfile: user/Dockerfile
    image: go-grpc-microservices/user
    container_name: user
    ports:
    - "50051:50051"
    environment:
    - "ACTIVITY_SERVICE_ADDR=activity:50051"
    - "PROJECT_SERVICE_ADDR=project:50051"
  task:
    build:
      context: ./
      dockerfile: task/Dockerfile
    image: go-grpc-microservices/task
    container_name: task
    ports:
    - "50052:50052"
    environment:
    - "ACTIVITY_SERVICE_ADDR=activity:50051"
    - "PROJECT_SERVICE_ADDR=project:50051"
    - "USER_SERVICE_ADDR=user:50051"
  project:
    build:
      context: ./
      dockerfile: project/Dockerfile
    image: go-grpc-microservices/project
    container_name: project
    ports:
    - "50053:50051"
    environment:
    - "ACTIVITY_SERVICE_ADDR=activity:50051"
    - "USER_SERVICE_ADDR=user:50051"
  